### ISSUE TITLE
mill bsp error

### ISSUE THREAD

**Issue by skinterqwe** [chipsalliance/playground#39]
build.sc:132: type ScalaTest is not a member of object mill.scalalib.TestModule
  object `integration-tests` extends Tests with TestModule.ScalaTest {
                                                           ^
build.sc:121: type ScalaTest is not a member of object mill.scalalib.TestModule
  object test extends Tests with TestModule.ScalaTest {
                                            ^
Compilation Failed

How to resolve this??
Tks

**Comment by ZenithalHourlyRate** [comment]
https://github.com/com-lihaoyi/mill/issues/1788

**Comment by skinterqwe** [comment]
The error above disappear, But new error appear,  I try mill version 0.10.0-0.10.7,  It does not work 


1 targets failed
mill.scalalib.GenIdea.idea java.lang.reflect.InvocationTargetException
    java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.base/java.lang.reflect.Method.invoke(Method.java:566)
    mill.define.Module$Internal.$anonfun$reflect$4(Module.scala:70)
    scala.collection.ArrayOps$WithFilter.map(ArrayOps.scala:90)
    mill.define.Module$Internal.reflect(Module.scala:62)
    mill.define.Module$Internal.reflectAll(Module.scala:73)
    mill.define.Module$Internal.reflectNestedObjects(Module.scala:81)
    mill.define.Module.millModuleDirectChildren$lzycompute(Module.scala:25)
    mill.define.Module.millModuleDirectChildren(Module.scala:25)
    mill.define.Module$Internal.rec$1(Module.scala:40)
    mill.define.Module$Internal.traverse(Module.scala:41)
    mill.define.Module$Internal.modules$lzycompute(Module.scala:44)
    mill.define.Module$Internal.modules(Module.scala:44)
    mill.define.Module$Internal.segmentsToModules$lzycompute(Module.scala:45)
    mill.define.Module$Internal.segmentsToModules(Module.scala:45)
    mill.scalalib.GenIdeaImpl.xmlFileLayout(GenIdeaImpl.scala:79)
    mill.scalalib.GenIdeaImpl.run(GenIdeaImpl.scala:43)

**Comment by skinterqwe** [comment]
Fix

**Comment by skinterqwe** [comment]
Fix
